package com.didoflores.capturacubagem;

import android.content.*;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.provider.MediaStore;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import androidx.core.content.FileProvider;import com.google.android.material.button.MaterialButton;import com.google.android.material.card.MaterialCardView;import com.google.android.material.progressindicator.LinearProgressIndicator;import com.google.mlkit.vision.common.InputImage;import com.google.mlkit.vision.text.TextRecognition;import com.google.mlkit.vision.text.latin.TextRecognizerOptions;import java.io.*;import java.text.DecimalFormat;import java.util.*;

public class MainActivity extends AppCompatActivity {
 final double LIMIT=68.0; double used=0; int productPhotos=0; Uri pendingUri; boolean cardMode=false; final ArrayList<String> rows=new ArrayList<>();
 TextView usedTv,leftTv,pctTv,cardText,photoCount,list; LinearProgressIndicator progress; EditText name,l,w,h,qty;
 int navy=Color.rgb(23,59,87), green=Color.rgb(47,125,109), bg=Color.rgb(246,248,250); DecimalFormat df=new DecimalFormat("0.000");
 @Override public void onCreate(Bundle b){super.onCreate(b); buildUi();}
 TextView tv(String s,int size,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(navy);v.setPadding(4,8,4,8);if(bold)v.setTypeface(null,1);return v;}
 EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(17);e.setSingleLine();e.setPadding(20,8,20,8);return e;}
 MaterialButton btn(String s){MaterialButton b=new MaterialButton(this);b.setText(s);b.setTextSize(16);b.setCornerRadius(22);b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(green));b.setLayoutParams(new LinearLayout.LayoutParams(-1,150));return b;}
 MaterialCardView card(){MaterialCardView c=new MaterialCardView(this);c.setRadius(28);c.setCardElevation(2);c.setUseCompatPadding(true);return c;}
 void buildUi(){ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(bg);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,24,28,40);scroll.addView(root);
  TextView title=tv("Captura & Cubagem",28,true);root.addView(title);root.addView(tv("Catálogo de fornecedores • Container 68 m³",14,false));
  MaterialCardView meter=card();LinearLayout m=new LinearLayout(this);m.setOrientation(LinearLayout.VERTICAL);m.setPadding(24,18,24,20);meter.addView(m);m.addView(tv("OCUPAÇÃO DO CONTAINER",13,true));usedTv=tv("0,000 / 68,000 m³",27,true);m.addView(usedTv);progress=new LinearProgressIndicator(this);progress.setMax(100);progress.setProgress(0);m.addView(progress);pctTv=tv("0% ocupado",15,true);leftTv=tv("Restam 68,000 m³",15,false);m.addView(pctTv);m.addView(leftTv);root.addView(meter);
  root.addView(tv("1. FORNECEDOR",18,true));MaterialButton cardBtn=btn("📇 Fotografar cartão de visitas");cardBtn.setOnClickListener(v->takePhoto(true));root.addView(cardBtn);cardText=tv("Nenhum cartão fotografado",14,false);root.addView(cardText);
  root.addView(tv("2. PRODUTO",18,true));MaterialButton photoBtn=btn("📷 Tirar foto do produto");photoBtn.setOnClickListener(v->takePhoto(false));root.addView(photoBtn);photoCount=0;TextView pc=tv("Fotos deste item: 0",14,false);photoCountView=pc;root.addView(pc);
  name=field("Nome / código do produto (opcional)");root.addView(name);LinearLayout dims=new LinearLayout(this);dims.setOrientation(LinearLayout.HORIZONTAL);l=field("Comp. cm");w=field("Larg. cm");h=field("Alt. cm");for(EditText e:new EditText[]{l,w,h}){e.setInputType(2|8192);e.setLayoutParams(new LinearLayout.LayoutParams(0,130,1));dims.addView(e);}root.addView(dims);qty=field("Quantidade");qty.setInputType(2);root.addView(qty);
  MaterialButton add=btn("＋ Adicionar ao container");add.setOnClickListener(v->addItem());root.addView(add);root.addView(tv("ITENS ADICIONADOS",18,true));list=tv("Nenhum item ainda.",14,false);root.addView(list);
  MaterialButton export=btn("✓ Finalizar e compartilhar catálogo");export.setOnClickListener(v->share());root.addView(export);setContentView(scroll);
 }
 TextView photoCountView;
 void takePhoto(boolean card){try{File dir=new File(getFilesDir(),"photos");dir.mkdirs();File f=new File(dir,(card?"cartao_":"produto_")+System.currentTimeMillis()+".jpg");pendingUri=FileProvider.getUriForFile(this,getPackageName()+".provider",f);cardMode=card;Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,pendingUri);i.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivityForResult(i,card?10:11);}catch(Exception e){Toast.makeText(this,"Não foi possível abrir a câmera",Toast.LENGTH_LONG).show();}}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||pendingUri==null)return;if(r==10){cardText.setText("Cartão salvo. Lendo dados…");try{InputImage im=InputImage.fromFilePath(this,pendingUri);TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS).process(im).addOnSuccessListener(t->cardText.setText("Dados do cartão:\n"+t.getText())).addOnFailureListener(e->cardText.setText("Cartão salvo ✓"));}catch(Exception e){cardText.setText("Cartão salvo ✓");}}else{productPhotos++;photoCountView.setText("Fotos deste item: "+productPhotos);}}
 double num(EditText e){return Double.parseDouble(e.getText().toString().replace(",","."));}
 void addItem(){try{double a=num(l),b=num(w),c=num(h);int q=Integer.parseInt(qty.getText().toString());if(a<=0||b<=0||c<=0||q<=0)throw new Exception();double unit=(a*b*c)/1000000d,total=unit*q;if(used+total>LIMIT){new android.app.AlertDialog.Builder(this).setTitle("Container acima de 68 m³").setMessage("Este item levará o total a "+df.format(used+total)+" m³. Deseja adicionar mesmo assim?").setPositiveButton("Adicionar",(x,y)->commit(a,b,c,q,total)).setNegativeButton("Cancelar",null).show();}else commit(a,b,c,q,total);}catch(Exception e){Toast.makeText(this,"Informe comprimento, largura, altura e quantidade.",Toast.LENGTH_LONG).show();}}
 void commit(double a,double b,double c,int q,double total){used+=total;String n=name.getText().toString().trim();if(n.isEmpty())n="Produto "+(rows.size()+1);rows.add(n+" | "+a+"×"+b+"×"+c+" cm | Qtd "+q+" | "+df.format(total)+" m³ | "+productPhotos+" foto(s)");update();name.setText("");l.setText("");w.setText("");h.setText("");qty.setText("");productPhotos=0;photoCountView.setText("Fotos deste item: 0");}
 void update(){double p=Math.min(100,(used/LIMIT)*100),left=Math.max(0,LIMIT-used);usedTv.setText(df.format(used)+" / 68,000 m³");pctTv.setText(Math.round(p)+"% ocupado");leftTv.setText("Restam "+df.format(left)+" m³");progress.setProgress((int)p);StringBuilder s=new StringBuilder();for(int i=0;i<rows.size();i++)s.append(i+1).append(". ").append(rows.get(i)).append("\n\n");list.setText(s.toString());}
 void share(){if(rows.isEmpty()){Toast.makeText(this,"Adicione pelo menos um produto.",Toast.LENGTH_SHORT).show();return;}try{File f=new File(getCacheDir(),"catalogo_cubagem.csv");FileWriter out=new FileWriter(f);out.write("Produto;Medidas;Quantidade;Cubagem m3;Fotos\n");for(String r:rows)out.write(r.replace(" | ",";")+"\n");out.write("TOTAL;;;"+df.format(used)+";\n");out.close();Uri u=FileProvider.getUriForFile(this,getPackageName()+".provider",f);Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/csv");i.putExtra(Intent.EXTRA_STREAM,u);i.putExtra(Intent.EXTRA_TEXT,"Catálogo Captura & Cubagem — "+df.format(used)+" m³ de 68 m³");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Compartilhar catálogo"));}catch(Exception e){Toast.makeText(this,"Erro ao gerar catálogo",Toast.LENGTH_LONG).show();}}
}
