plugins { id 'com.android.application' }

android { namespace 'com.didoflores.capturacubagem'; compileSdk 35
    defaultConfig { applicationId 'com.didoflores.capturacubagem'; minSdk 24; targetSdk 35; versionCode 2; versionName '2.0' }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.google.mlkit:text-recognition:16.0.1'
}
